In [1]:
!pip install numpy

In [2]:
import numpy as np

In [54]:
a = np.array([[1, 2, 3], [6, 7, 8]])
print(a)
print(a.ndim)
print(a.shape)
print(np.shape(a))
print(a.size)
print(a.dtype)

[[1 2 3]
 [6 7 8]]
2
(2, 3)
(2, 3)
6
int64


In [12]:
b = np.arange(0,10,2)
print(b)

c = np.linspace(0,10,5)
print(c)

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [14]:
d = np.zeros(5)
print(d)

e = np.ones(6)
print(e)

f = np.eye(7)
print(f)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [15]:
a[0][1] = 4
print(a)

[[1 4 3]
 [6 7 8]]


In [17]:
a[:,0] = [9,9]
print(a)

[[9 4 3]
 [9 7 8]]


In [18]:
g = np.transpose(a)
print(g)

[[9 9]
 [4 7]
 [3 8]]


In [19]:
j = np.array([1,2,3,4])
j1 = np.delete(j,3)
j2 = j[0:3]
print(j)
print(j1)
print(j2)

[1 2 3 4]
[1 2 3]
[1 2 3]


In [26]:
i = np.array([[1,2,3], [4,5,6]])
print(i)
i1 = np.delete(i,2,1)
print(i1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [30]:
k = np.array([1,2,3,4,5,6])
print(k)
l = k.reshape(2,3)
print(l)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Векторы

In [32]:
x = np.array([1,2,3,4])
x1 = x + 4
print(x1)

x2 = x + x1
print(x2)

[5 6 7 8]
[ 6  8 10 12]


In [34]:
z = np.array([[20, 10], [17, 22]])
z1 = np.array([350, 500])
y = np.linalg.solve(z,z1)
print(y)

[10. 15.]


In [43]:
k1 = np.array([1,2,3])
k2 = np.array([4,5,6])
k3 = np.add(k1,k2)
print(k3)
k4 = np.subtract(k1,k2)
print(k4)
k5 = np.negative(k2)
print(k5)
k6 = np.multiply(k1,k2)
print(k6)
k7 = np.divide(k1,k2)
print(k7)
k8 = np.floor_divide(k1,k2)
print(k8)
k9 = np.power(k1,k2)
print(k9)

[5 7 9]
[-3 -3 -3]
[-4 -5 -6]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[  1  32 729]


In [48]:
n = np.array([2,5,7,13,54,13])
n1 = np.sum(n)
n2 = np.mean(n)
n3 = np.std(n)
n4 = np.var(n)
n5 = np.min(n)
n6 = np.max(n)
n7 = np.argmin(n)
n8 = np.argmax(n)
n9 = np.cumsum(n)
n10 = np.cumprod(n)
print(n1)
print(n2)
print(n3)
print(n4)
print(n5)
print(n6)
print(n7)
print(n8)
print(n9)
print(n10)

n11 = np.unique(n)
print(n11)

94
15.666666666666666
17.603661235347857
309.88888888888886
2
54
0
4
[ 2  7 14 27 81 94]
[     2     10     70    910  49140 638820]
[ 2  5  7 13 54]


In [49]:
o1 = np.array([4,5,7,2])
o2 = np.array([1,2,2,5])
o3 = np.intersect1d(o1,o2)
o4 = np.union1d(o1,o2)
o5 = np.setdiff1d(o1,o2)
o6 = np.setxor1d(o1,o2)

print(o3)
print(o4)
print(o5)
print(o6)

[2 5]
[1 2 4 5 7]
[4 7]
[1 4 7]


In [52]:
y1 = np.array([1,3,5,8])
y2 = np.array([3,632,1,7])
y3 = np.dot(y1,y2)
print(y3)

1960


In [53]:
print(np.array([1,2,3,4])[-1])

4


In [62]:
array = np.arange(10) ** 4
print(array)
array_2 = np.arange(10) **3
print(array_2)
array_sum = np.sum(np.add(array,array_2))
print(array_sum)

array_difference = np.sum(np.subtract(array,array_2))
print(array_difference)

game_payments2 = array[1]
print(game_payments2)

subscription_last = array_2[-1]
print(subscription_last)

[   0    1   16   81  256  625 1296 2401 4096 6561]
[  0   1   8  27  64 125 216 343 512 729]
17358
13308
1
729


In [88]:
some_data =  [
    [3, 8, 1, 0, 1, 2],
    [9, 2, 7, 3, 0, 4],
    [2, 5, 1, 3, 1, 8],
    [5, 1, 2, 1, 1, 0]
]
some_data = np.array(some_data)
print(some_data)
array_sum = np.sum(some_data)
print(array_sum)
array_t = np.transpose(some_data)
print(array_t)
array_avg = np.mean(some_data)
print(array_avg)
lines = np.delete(some_data, 0, 0)
print(lines)

last_column = some_data[:, 5]
print(last_column)



[[3 8 1 0 1 2]
 [9 2 7 3 0 4]
 [2 5 1 3 1 8]
 [5 1 2 1 1 0]]
70
[[3 9 2 5]
 [8 2 5 1]
 [1 7 1 2]
 [0 3 3 1]
 [1 0 1 1]
 [2 4 8 0]]
2.9166666666666665
[[9 2 7 3 0 4]
 [2 5 1 3 1 8]
 [5 1 2 1 1 0]]
[2 4 8 0]


In [90]:
A = np.array([[3,2,1], [1,6,2], [4,1,5]])
B = np.array([360,300,675])
print(A)
C = np.linalg.solve(A,B)
print(C)

[[3 2 1]
 [1 6 2]
 [4 1 5]]
[90. 15. 60.]
